# Generated by Django 5.2.4 on 2025-07-22 07:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmessage',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ارسال'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendmessage',
            name='message',
            field=models.TextField(default=1, verbose_name='پیام'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendmessage',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
