# Generated by Django 5.2.4 on 2025-07-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_module', '0003_remove_sendmessage_user_chat_sendmessage_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmessage',
            name='sender',
            field=models.CharField(choices=[('user', 'User'), ('ai', 'AI')], default=1, max_length=4),
            preserve_default=False,
        ),
    ]
